services:
  storage:
    build:
      dockerfile: ./Dockerfile.ton-storage
    volumes:
      - .docker-volumes/ton-storage:/usr/ton-storage/storage-db/:rw
      - .docker-volumes/upload:/usr/ton-storage/upload/:ro

  service:
    build:
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .docker-volumes/ton-storage/cli-keys/:/usr/ton-storage/storage-db/cli-keys/:ro
      - .docker-volumes/upload/:/usr/ton-storage/upload/:rw
    environment:
      TON_STORAGE_HOST: storage
    depends_on:
      - storage

  https-portal:
    image:  steveltn/https-portal:1
    ports:
        - "80:80"
        - "443:443"
    restart: always
    environment:
        # TODO: Replace localhost with your domain name or server IP
        DOMAINS:  "localhost -> http://service:3000"
        # STAGE: 'production' # Don't use production until staging works
        # FORCE_RENEW: 'true'
    depends_on:
        - service
