services:
  storage:
    build:
      dockerfile: ./Dockerfile.ton-storage
    volumes:
      - .docker-volumes/ton-storage:/usr/ton-storage/storage-db/:rw
      - .docker-volumes/upload/:/usr/src/app/.upload/:ro

  service:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .docker-volumes/ton-storage/cli-keys/:/usr/ton-storage/storage-db/cli-keys/:ro
      - .docker-volumes/upload/:/usr/src/app/.upload/:rw
    environment:
      TON_STORAGE_HOST: storage
      STORAGE_CLI_EXEC_PATH: ./storage-daemon-cli
      STORAGE_WORK_DIR: /usr/ton-storage/
      USE_SHELL: 'true'
    depends_on:
      - storage
